name: Release MacOS binaries
'on':
  release:
    types:
      - published
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build: [macos-x86_64, macos-aarch64]
        include:
        - build: macos-x86_64
          os: macos-13
          target: x86_64-apple-darwin
        - build: macos-aarch64
          os: macos-14
          target: aarch64-apple-darwin
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      
      - name: Install Dependencies
        run: |
          brew install \
            cmake \
            brotli \
            lcms2 \
            highway \
            asciidoc \
            python \
            googletest

      - name: Configure
        run: |
          cmake -S . -B build \
            -DCMAKE_PREFIX_PATH="$(brew --prefix googletest)" \
            -DJPEGXL_FORCE_SYSTEM_BROTLI=ON \
            -DJPEGXL_FORCE_SYSTEM_LCMS2=ON \
            -DJPEGXL_FORCE_SYSTEM_HWY=ON \
            -DJPEGXL_ENABLE_DEVTOOLS=ON \
            -DJPEGXL_ENABLE_JNI=OFF \
            -DJPEGXL_ENABLE_JPEGLI=OFF \
            -DJPEGXL_ENABLE_SKCMS=OFF \
            -DJPEGXL_ENABLE_MANPAGES=ON

      - name: Build
        run: cmake --build build --config Release -j$(nproc)

      - name: Package
        run: |
          cd build
          cpack -G ZIP

      - name: Build archive
        shell: bash
        run: >
          staging="package-${{ github.event.release.tag_name }}-${{ matrix.target }}"

          mkdir "$staging"

          cp README.md "$staging/"

          tar czf "$staging.tar.gz" -C "$staging" .

          echo "ASSET=$staging.tar.gz" >> $GITHUB_ENV
          
      - name: Upload release archive
        uses: actions/upload-release-asset@e8f9f06c4b078e705bd2ea027f0926603fc9b4d5
        env:
          GITHUB_TOKEN: '${{ secrets.WITH_GITHUB_TOKEN }}'
        with:
          upload_url: '${{ github.event.release.upload_url }}'
          asset_path: '${{ env.ASSET }}'
          asset_name: '${{ env.ASSET }}'
          asset_content_type: application/octet-stream
