name: Release MacOS binaries
'on':
  release:
    types:
      - published
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build: [macos-x86_64]
        include:
        - build: macos-x86_64
          os: macos-13
          target: x86_64-apple-darwin
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      
      - name: Download sjpeg from github
        run: |
          echo 'hello world'
          
      - name: install denpendencies
        run: |
          brew install asciidoc
          brew install cmake
          brew install docbook-xsl
          brew install doxygen
          brew install pkgconf
          brew install sphinx-doc
          brew install brotli
          brew install giflib
          brew install highway
          brew install imath
          brew install jpeg-turbo
          brew install libpng
          brew install little-cms2
          brew install openexr
          brew install webp
      
      - name: Use CMake build project
        run: |
          cmake -S . -B build -DJPEGXL_FORCE_SYSTEM_BROTLI=ON -DJPEGXL_FORCE_SYSTEM_LCMS2=ON -DJPEGXL_FORCE_SYSTEM_HWY=ON -DJPEGXL_ENABLE_DEVTOOLS=ON -DJPEGXL_ENABLE_JNI=OFF -DJPEGXL_ENABLE_JPEGLI=OFF -DJPEGXL_ENABLE_SKCMS=OFF -DJPEGXL_VERSION=0.11.1 -DJPEGXL_ENABLE_MANPAGES=ON
          cmake --build build
          cmake --build build --target install
      
      - name: Install jpeg-xl
        run: |
          brew install jpeg-xl

      - name: Build archive
        shell: bash
        run: >
          staging="package-${{ github.event.release.tag_name }}-${{ matrix.target }}"

          mkdir "$staging"

          cjxl img/view.jpg view.jxl

          cp {img/view.jpg,view.jxl} "$staging/"

          tar czf "$staging.tar.gz" -C "$staging" .

          echo "ASSET=$staging.tar.gz" >> $GITHUB_ENV
          
      - name: Upload release archive
        uses: actions/upload-release-asset@e8f9f06c4b078e705bd2ea027f0926603fc9b4d5
        env:
          GITHUB_TOKEN: '${{ secrets.WITH_GITHUB_TOKEN }}'
        with:
          upload_url: '${{ github.event.release.upload_url }}'
          asset_path: '${{ env.ASSET }}'
          asset_name: '${{ env.ASSET }}'
          asset_content_type: application/octet-stream
